version: '3.8'

services:
  mysql:
    build: ./database
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend-container
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: