version: '3.8'

services:
  mysql:
    build: ./database
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Senha123
    ports:
      - "3307:3306"  # ← MUDOU porta para evitar conflito
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSenha123"]
      timeout: 10s
      retries: 5
      interval: 10s

  backend:
    build: ./backend
    container_name: backend-container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge